language: objective-c
osx_image: xcode7.3
script:
  - xcodebuild -project gitflow.xcodeproj -scheme gitflow -sdk macosx build test GCC_GENERATE_TEST_COVERAGE_FILES=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)

